# Generated by Django 5.2.14 on 2026-06-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_about_bio_fields_and_new_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_name_display', models.CharField(default='Karu Praneeth Kumar', max_length=100)),
                ('hero_roles', models.TextField(default='Agentic AI Engineer\nML Practitioner\nFull Stack Developer', help_text='One role per line. These rotate in the hero.')),
                ('hero_description', models.TextField(default='Building agentic AI systems, MCP pipelines, and intelligent automation tools. Final-year B.Tech CSE-AI @ SJCET Bengaluru. Open to agentic AI engineering roles and startup internships.', help_text='Short paragraph shown below the title.')),
                ('hero_cta_primary_label', models.CharField(default='Begin the Story', max_length=50)),
                ('hero_cta_primary_url', models.CharField(default='/about/', max_length=200)),
                ('hero_cta_secondary_label', models.CharField(default='View the Work', max_length=50)),
                ('hero_cta_secondary_url', models.CharField(default='/projects/', max_length=200)),
                ('github_url', models.URLField(blank=True, default='https://github.com/BunnyPraneeth5')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/in/karu-praneeth-kumar')),
                ('kaggle_url', models.URLField(blank=True, default='https://www.kaggle.com/bunnypraneeth5')),
                ('hackerrank_url', models.URLField(blank=True, default='https://hackerrank.com/profile/karu_praneeth')),
                ('leetcode_url', models.URLField(blank=True, default='https://leetcode.com/u/praneethkumar_/')),
                ('contact_email', models.EmailField(default='karupraneethkumar@gmail.com', max_length=254)),
                ('contact_location', models.CharField(default='Andhra Pradesh, India', max_length=100)),
                ('contact_tagline', models.CharField(default='A quiet place for the next conversation.', max_length=200)),
                ('contact_form_active', models.BooleanField(default=True, help_text='Uncheck to hide the form and show email link only.')),
                ('meta_title', models.CharField(blank=True, max_length=100)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
