# Generated by Django 5.2.14 on 2026-06-01 06:30

from django.db import migrations, models


def seed_admin_projects(apps, schema_editor):
    Project = apps.get_model('portfolio', 'Project')

    for project in Project.objects.all():
        updates = []
        if not project.short_description and project.description:
            project.short_description = project.description
            updates.append('short_description')
        if not project.tech_tags and project.technologies:
            project.tech_tags = project.technologies
            updates.append('tech_tags')
        if not project.live_demo_url and project.live_url:
            project.live_demo_url = project.live_url
            updates.append('live_demo_url')
        if not project.thumbnail and project.image:
            project.thumbnail = project.image
            updates.append('thumbnail')
        if project.featured and not project.is_featured:
            project.is_featured = True
            updates.append('is_featured')
        if updates:
            project.save(update_fields=updates)

    defaults = [
        {
            'title': 'SOC Copilot',
            'short_description': 'An agentic AI-powered Security Operations Center assistant built with a four-agent MCP pipeline (ReconAgent, ReputationAgent, ShodanAgent, ReportAgent). Achieves 99.88% intrusion detection accuracy on the CICIDS2017 dataset using ensemble ML. Features asyncio parallel agent execution, 6-hour diskcache TTL, and a PyQt6 desktop GUI.',
            'tech_tags': 'Python, MCP, PyQt6, Scikit-learn, Agentic AI',
            'github_url': 'https://github.com/bunnypraneeth5/SOC-Copilot',
            'is_featured': True,
            'is_published': True,
            'order': 0,
            'metric_kicker': 'MCP PIPELINE',
            'metric_1_value': '99.88%',
            'metric_1_label': 'Detection Accuracy',
            'metric_2_value': '84',
            'metric_2_label': 'Features Analyzed',
            'metric_3_value': '4',
            'metric_3_label': 'MCP Agents',
        },
        {
            'title': 'College Gate Pass System',
            'short_description': 'Built a secure gate pass system using QR authentication, reducing unauthorized entries by 75%.',
            'tech_tags': 'Django, Python, QR Auth',
            'github_url': 'https://github.com/BunnyPraneeth5/gate-pass',
            'is_featured': False,
            'is_published': True,
            'order': 10,
            'secondary_kicker': 'ACCESS CONTROL',
            'metric_1_value': '75%',
            'metric_1_label': 'entry risk reduced',
        },
        {
            'title': 'Car Sales Price Prediction',
            'short_description': 'Created a neural network to predict car prices with 88% accuracy, using feature engineering and visualization tools.',
            'tech_tags': 'TensorFlow, ANN, ML',
            'github_url': 'https://github.com/BunnyPraneeth5/Car-Sales-Prediction',
            'live_demo_url': 'https://Car-Sales-Price-Prediction.onrender.com',
            'is_featured': False,
            'is_published': True,
            'order': 20,
            'secondary_kicker': 'PREDICTIVE MODEL',
            'metric_1_value': '88%',
            'metric_1_label': 'model accuracy',
        },
        {
            'title': 'AI-Generated Fitness Website',
            'short_description': 'Built with AI tools, featuring 50+ components and rapid UI generation workflows. Backend integration in progress.',
            'tech_tags': 'v0.dev, ChatGPT, AI Tools',
            'live_demo_url': 'https://v0.dev/chat/fork-of-workout-website-FLvlcsE2hGL',
            'is_featured': False,
            'is_published': True,
            'order': 30,
            'secondary_kicker': 'AI WORKFLOW',
        },
    ]

    for item in defaults:
        legacy_defaults = {
            'description': item['short_description'],
            'technologies': item['tech_tags'],
            'live_url': item.get('live_demo_url', ''),
            'featured': item['is_featured'],
        }
        project_defaults = {**legacy_defaults, **item}
        Project.objects.update_or_create(
            title=item['title'],
            defaults=project_defaults,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_sitesettings_alter_project_options_project_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='live_demo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=models.TextField(blank=True, help_text='Optional extended case study text.'),
        ),
        migrations.AddField(
            model_name='project',
            name='metric_1_label',
            field=models.CharField(blank=True, help_text='e.g. Detection Accuracy', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='metric_1_value',
            field=models.CharField(blank=True, help_text='e.g. 99.88%', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='metric_2_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='metric_2_value',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='metric_3_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='metric_3_value',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='metric_kicker',
            field=models.CharField(blank=True, help_text='Small label above metrics, e.g. MCP PIPELINE.', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='secondary_kicker',
            field=models.CharField(blank=True, help_text='Small label above non-featured project titles.', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(blank=True, help_text='Shown in the project card.'),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_tags',
            field=models.CharField(blank=True, help_text='Comma-separated. e.g. Python, MCP, PyQt6', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower number appears first.'),
        ),
        migrations.RunPython(seed_admin_projects, migrations.RunPython.noop),
    ]
