# Generated by Django 5.2.14 on 2026-06-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_project_description_alter_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile image used in the homepage hero.', null=True, upload_to='appearance/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='resume',
            field=models.FileField(blank=True, help_text='Resume PDF linked from the site.', null=True, upload_to='resume/'),
        ),
    ]
