# Generated by Django 5.2.14 on 2026-06-02 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_sitesettings_profile_image_sitesettings_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='event_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
