# Generated by Django 5.2.16 on 2026-08-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_blogpost_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='siteappearance',
            name='hero_description',
        ),
        migrations.RemoveField(
            model_name='siteappearance',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='siteappearance',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='siteappearance',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='siteappearance',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='siteappearance',
            name='typewriter_phrases',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='percentage',
        ),
        migrations.AddField(
            model_name='skill',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on homepage'),
        ),
    ]
