# Generated by Django 5.2.16 on 2026-08-10 15:43

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Project = apps.get_model('portfolio', 'Project')
    seen = set()
    for project in Project.objects.order_by('pk'):
        base = slugify(project.title) or 'project'
        slug = base
        suffix = 2
        while slug in seen or Project.objects.filter(slug=slug).exclude(pk=project.pk).exists():
            slug = f'{base}-{suffix}'
            suffix += 1
        seen.add(slug)
        project.slug = slug
        project.save(update_fields=['slug'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_about_image_remove_about_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.RunPython(populate_slugs, noop),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
