# Generated by Django 5.2.16 on 2026-08-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_remove_project_description_remove_project_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notice_period',
            field=models.CharField(blank=True, default='Immediate', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='open_to_internship',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='open_to_remote',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='open_to_work',
            field=models.BooleanField(default=True, help_text='Show as actively looking on the pet chat'),
        ),
    ]
